create table "public"."file_quality_rules" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "topic" text default 'defualt'::text,
    "attribute_rules" json,
    "content_rules" json
);


alter table "public"."file_quality_rules" enable row level security;

create table "public"."file_upload_queue" (
    "id" uuid not null default gen_random_uuid(),
    "created_at" timestamp with time zone not null default now(),
    "target_collection_id" uuid
);


alter table "public"."file_upload_queue" enable row level security;

CREATE UNIQUE INDEX file_quality_rules_pkey ON public.file_quality_rules USING btree (id);

CREATE UNIQUE INDEX file_upload_queue_pkey ON public.file_upload_queue USING btree (id);

alter table "public"."file_quality_rules" add constraint "file_quality_rules_pkey" PRIMARY KEY using index "file_quality_rules_pkey";

alter table "public"."file_upload_queue" add constraint "file_upload_queue_pkey" PRIMARY KEY using index "file_upload_queue_pkey";

alter table "public"."file_upload_queue" add constraint "public_file_upload_queue_target_collection_id_fkey" FOREIGN KEY (target_collection_id) REFERENCES collections(id) ON UPDATE CASCADE ON DELETE SET NULL not valid;

alter table "public"."file_upload_queue" validate constraint "public_file_upload_queue_target_collection_id_fkey";

grant delete on table "public"."file_quality_rules" to "anon";

grant insert on table "public"."file_quality_rules" to "anon";

grant references on table "public"."file_quality_rules" to "anon";

grant select on table "public"."file_quality_rules" to "anon";

grant trigger on table "public"."file_quality_rules" to "anon";

grant truncate on table "public"."file_quality_rules" to "anon";

grant update on table "public"."file_quality_rules" to "anon";

grant delete on table "public"."file_quality_rules" to "authenticated";

grant insert on table "public"."file_quality_rules" to "authenticated";

grant references on table "public"."file_quality_rules" to "authenticated";

grant select on table "public"."file_quality_rules" to "authenticated";

grant trigger on table "public"."file_quality_rules" to "authenticated";

grant truncate on table "public"."file_quality_rules" to "authenticated";

grant update on table "public"."file_quality_rules" to "authenticated";

grant delete on table "public"."file_quality_rules" to "service_role";

grant insert on table "public"."file_quality_rules" to "service_role";

grant references on table "public"."file_quality_rules" to "service_role";

grant select on table "public"."file_quality_rules" to "service_role";

grant trigger on table "public"."file_quality_rules" to "service_role";

grant truncate on table "public"."file_quality_rules" to "service_role";

grant update on table "public"."file_quality_rules" to "service_role";

grant delete on table "public"."file_upload_queue" to "anon";

grant insert on table "public"."file_upload_queue" to "anon";

grant references on table "public"."file_upload_queue" to "anon";

grant select on table "public"."file_upload_queue" to "anon";

grant trigger on table "public"."file_upload_queue" to "anon";

grant truncate on table "public"."file_upload_queue" to "anon";

grant update on table "public"."file_upload_queue" to "anon";

grant delete on table "public"."file_upload_queue" to "authenticated";

grant insert on table "public"."file_upload_queue" to "authenticated";

grant references on table "public"."file_upload_queue" to "authenticated";

grant select on table "public"."file_upload_queue" to "authenticated";

grant trigger on table "public"."file_upload_queue" to "authenticated";

grant truncate on table "public"."file_upload_queue" to "authenticated";

grant update on table "public"."file_upload_queue" to "authenticated";

grant delete on table "public"."file_upload_queue" to "service_role";

grant insert on table "public"."file_upload_queue" to "service_role";

grant references on table "public"."file_upload_queue" to "service_role";

grant select on table "public"."file_upload_queue" to "service_role";

grant trigger on table "public"."file_upload_queue" to "service_role";

grant truncate on table "public"."file_upload_queue" to "service_role";

grant update on table "public"."file_upload_queue" to "service_role";


